---
title: "NY weather flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
library needed
```{r, message=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(p8105.datasets)

```

data upload
```{r}
data("ny_noaa")
head(ny_noaa)
```


data cleaning
```{r}
weather_df = ny_noaa |>
  mutate(
    tmax = as.numeric(tmax) / 10, 
    tmin = as.numeric(tmin) / 10,
    prcp = as.numeric(prcp) / 10, 
    year = as.numeric(format(date, "%Y")),
    month = as.numeric(format(date, "%m"))
  ) |>
  drop_na(tmax, tmin, prcp)

weather_df
```
### Chart A
comparision of monthly max min temperature
```{r}
avg_temp = weather_df |>
group_by(year, month) |>
summarise(
mean_tmax = mean(tmax, na.rm = TRUE),
mean_tmin = mean(tmin, na.rm = TRUE)
) |>
filter(year >= 2010) |>
pivot_longer(cols = c(mean_tmax, mean_tmin),
names_to = "Temp_Type",
values_to = "Temperature") |>
plot_ly(
x = ~month,
y = ~Temperature,
color = ~interaction(year, Temp_Type),
type = 'scatter',
mode = 'lines+markers'
) |>
layout(
title = "Average Monthly Max & Min Temperature (≥2010)",
xaxis = list(title = "Month"),
yaxis = list(title = "Temperature (°C)")
)

avg_temp
```


### Chart B
Monthly Precipitation in 2010
```{r}
monthly_prcp = weather_df |>
group_by(year, month) |>
summarise(mean_prcp = mean(prcp, na.rm = TRUE)) |>
filter(year == 2010)

plot_ly(
monthly_prcp,
x = ~month,
y = ~mean_prcp,
type = "bar",
color = ~factor(month)
) |>
layout(
title = "Average Monthly Precipitation (2010)",
xaxis = list(title = "Month"),
yaxis = list(title = "Mean Precipitation (mm)")
)
```

### Chart C
precipitation comparision based on monthly data in 2009 and 2010
```{r}

monthly_avg_prcp = weather_df |>
  filter(year %in% c(2009, 2010)) |>
  group_by(year, month) |>
  summarise(mean_prcp = mean(prcp, na.rm = TRUE), .groups = "drop")


plot_ly(
  data = monthly_avg_prcp,
  x = ~factor(year),      
  y = ~mean_prcp,         
  color = ~factor(year),
  type = "box"
) |>
layout(
  title = "Distribution of Monthly Average Precipitation (2009 vs 2010)",
  xaxis = list(title = "Year"),
  yaxis = list(title = "Monthly Average Precipitation (mm)")
)


```

